kind: pipeline
type: docker
name: Build-Pipeline

steps:
- name: Test-${DRONE_TAG}
  image: node:18
  commands:
    - yarn install --ignore-scripts
    - npx gulp fix-masterpage
    - npx gulp fix-types
    - yarn tsc
    - yarn test
    - yarn build
  settings:
    mtu: 1450
  when:
    ref:
      include:
      - refs/tags/*
    branch:
      exclude:
      - main
- name: push commit
  image: appleboy/drone-git-push
  settings:
    remote_name: origin
    commit: true
    commit_message: Tests Passed - ${DRONE_COMMIT_MESSAGE}
    branch: ${DRONE_BRANCH}
  when:
    status:
    - success
    ref:
      include:
      - refs/tags/*
    branch:
      exclude:
      - main
- name: Notify-via-Telegram
  image: appleboy/drone-telegram
  settings:
    mtu: 1450
    token:
      from_secret: telegram_token
    to: 
      from_secret: telegram_default_groupe_id
    message_file: .drone/telegram_prod_build.tpl
  when:
    status:
    - failure
    - success
    ref:
      include:
      - refs/tags/*
    branch:
      exclude:
      - main
- name: Notify-via-Mail
  image: drillster/drone-email
  settings:
    mtu: 1450
    host: smtp.gmail.com
    username:
      from_secret: gmail_user
    password:
      from_secret: gmail_pass
    from: admin@integralschweiz.org
    recipients: []
    recipients_only: true
    body: file:///drone/src/.drone/mail_prod_build.hbs
    when:
      status: [ changed, failure, success ]
  when:
    status:
    - failure
    - success
    ref:
      include:
      - refs/tags/*
    branch:
      exclude:
      - main
trigger:
  event:
  - tag
############Production Deploy only##########
---
kind: pipeline
type: docker
name: Deploy-Production

steps:
- name: Create-Pull-Request & Merge
  image: registry.integral-systems.ch/integral-systems/alpine:github-client-alpine
  environment:
    GH_TOKEN:
      from_secret: github_api_token
  commands:
    - gh pr create --base main --head dev --title "Automated Pull Request ${DRONE_TAG}" --body "This pull request is for version ${DRONE_TAG} with the commit message ${DRONE_COMMIT_MESSAGE}"
    - PR_NUMBER=$(gh pr list --base main --head dev --json number --jq '.[0].number')
    - gh pr merge "$PR_NUMBER" --auto --merge
#############Notification###################
- name: Notify-via-Telegram
  image: appleboy/drone-telegram
  settings:
    mtu: 1450
    token:
      from_secret: telegram_token
    to: 
      from_secret: telegram_default_groupe_id
    message_file: .drone/telegram_prod_deploy.tpl
  when:
    status:
    - failure
    - success
- name: Notify-via-Mail
  image: drillster/drone-email
  settings:
    mtu: 1450
    host: smtp.gmail.com
    username:
      from_secret: gmail_user
    password:
      from_secret: gmail_pass
    from: admin@integralschweiz.org
    recipients: []
    recipients_only: true
    body: file:///drone/src/.drone/mail_prod_deploy.hbs
    when:
      status: [ changed, failure, success ]
  when:
    status:
    - failure
    - success
# - name: Update-Rollbar-Deploy
#   image: plugins/webhook
#   settings:
#     mtu: 1450
#     urls: https://api.rollbar.com/api/1/deploy
#     headers:
#       - "X-Rollbar-Access-Token=675b85f9093e4099b89376f4a973bca8"
#     template: |
#       {
#         "environment": "production",
#         "revision": "{{build.commit}}",
#         "rollbar_username": "{{build.author}}",
#         "local_username": "{{build.author}}",
#         "comment": "{{build.message}}",
#         "status": "succeeded"
#       }   
trigger:
  event:
  - promote
  target:
  - production 
